// This file is auto-generated by @hey-api/openapi-ts

import { type Options as ClientOptions, type TDataShape, type Client, urlSearchParamsBodySerializer } from '@hey-api/client-axios';
import type { RegisterUserUsersRegistrationPostData, RegisterUserUsersRegistrationPostError, ReadUserMeUsersMeGetData, ReadUserMeUsersMeGetResponse, ImagesGeminiAnalyzeImagesPostData, ImagesGeminiAnalyzeImagesPostError, LoginTokenAuthTokenPostData, LoginTokenAuthTokenPostResponse, LoginTokenAuthTokenPostError, GetShiftsShiftGetMoreGetData, GetShiftsShiftGetMoreGetResponse, GetShiftsShiftGetMoreGetError, GetShiftShiftGetGetData, GetShiftShiftGetGetResponse, GetShiftShiftGetGetError, InsertShiftShiftInsertPostData, InsertShiftShiftInsertPostResponse, InsertShiftShiftInsertPostError, RemoveShiftShiftDeleteDeleteData, RemoveShiftShiftDeleteDeleteError, UpdateShiftShiftUpdatePutData, UpdateShiftShiftUpdatePutResponse, UpdateShiftShiftUpdatePutError } from './types.gen';
import { client as _heyApiClient } from './client.gen';

export type Options<TData extends TDataShape = TDataShape, ThrowOnError extends boolean = boolean> = ClientOptions<TData, ThrowOnError> & {
    /**
     * You can provide a client instance returned by `createClient()` instead of
     * individual options. This might be also useful if you want to implement a
     * custom client.
     */
    client?: Client;
    /**
     * You can pass arbitrary values through the `meta` object. This can be
     * used to access values that aren't defined as part of the SDK function.
     */
    meta?: Record<string, unknown>;
};

/**
 * Register User
 */
export const registerUserUsersRegistrationPost = <ThrowOnError extends boolean = false>(options: Options<RegisterUserUsersRegistrationPostData, ThrowOnError>) => {
    return (options.client ?? _heyApiClient).post<unknown, RegisterUserUsersRegistrationPostError, ThrowOnError>({
        url: '/users/registration',
        ...options,
        headers: {
            'Content-Type': 'application/json',
            ...options?.headers
        }
    });
};

/**
 * Read User Me
 */
export const readUserMeUsersMeGet = <ThrowOnError extends boolean = false>(options?: Options<ReadUserMeUsersMeGetData, ThrowOnError>) => {
    return (options?.client ?? _heyApiClient).get<ReadUserMeUsersMeGetResponse, unknown, ThrowOnError>({
        security: [
            {
                scheme: 'bearer',
                type: 'http'
            }
        ],
        url: '/users/me',
        ...options
    });
};

/**
 * Images
 */
export const imagesGeminiAnalyzeImagesPost = <ThrowOnError extends boolean = false>(options: Options<ImagesGeminiAnalyzeImagesPostData, ThrowOnError>) => {
    return (options.client ?? _heyApiClient).post<unknown, ImagesGeminiAnalyzeImagesPostError, ThrowOnError>({
        security: [
            {
                scheme: 'bearer',
                type: 'http'
            }
        ],
        url: '/gemini/analyze_images',
        ...options,
        headers: {
            'Content-Type': 'application/json',
            ...options?.headers
        }
    });
};

/**
 * Login Token
 */
export const loginTokenAuthTokenPost = <ThrowOnError extends boolean = false>(options: Options<LoginTokenAuthTokenPostData, ThrowOnError>) => {
    return (options.client ?? _heyApiClient).post<LoginTokenAuthTokenPostResponse, LoginTokenAuthTokenPostError, ThrowOnError>({
        ...urlSearchParamsBodySerializer,
        url: '/auth/token',
        ...options,
        headers: {
            'Content-Type': 'application/x-www-form-urlencoded',
            ...options?.headers
        }
    });
};

/**
 * Get Shifts
 */
export const getShiftsShiftGetMoreGet = <ThrowOnError extends boolean = false>(options: Options<GetShiftsShiftGetMoreGetData, ThrowOnError>) => {
    return (options.client ?? _heyApiClient).get<GetShiftsShiftGetMoreGetResponse, GetShiftsShiftGetMoreGetError, ThrowOnError>({
        security: [
            {
                scheme: 'bearer',
                type: 'http'
            }
        ],
        url: '/shift/get_more',
        ...options
    });
};

/**
 * Get Shift
 */
export const getShiftShiftGetGet = <ThrowOnError extends boolean = false>(options: Options<GetShiftShiftGetGetData, ThrowOnError>) => {
    return (options.client ?? _heyApiClient).get<GetShiftShiftGetGetResponse, GetShiftShiftGetGetError, ThrowOnError>({
        security: [
            {
                scheme: 'bearer',
                type: 'http'
            }
        ],
        url: '/shift/get',
        ...options,
        headers: {
            'Content-Type': 'application/json',
            ...options?.headers
        }
    });
};

/**
 * Insert Shift
 */
export const insertShiftShiftInsertPost = <ThrowOnError extends boolean = false>(options: Options<InsertShiftShiftInsertPostData, ThrowOnError>) => {
    return (options.client ?? _heyApiClient).post<InsertShiftShiftInsertPostResponse, InsertShiftShiftInsertPostError, ThrowOnError>({
        security: [
            {
                scheme: 'bearer',
                type: 'http'
            }
        ],
        url: '/shift/insert',
        ...options,
        headers: {
            'Content-Type': 'application/json',
            ...options?.headers
        }
    });
};

/**
 * Remove Shift
 */
export const removeShiftShiftDeleteDelete = <ThrowOnError extends boolean = false>(options: Options<RemoveShiftShiftDeleteDeleteData, ThrowOnError>) => {
    return (options.client ?? _heyApiClient).delete<unknown, RemoveShiftShiftDeleteDeleteError, ThrowOnError>({
        security: [
            {
                scheme: 'bearer',
                type: 'http'
            }
        ],
        url: '/shift/delete',
        ...options
    });
};

/**
 * Update Shift
 */
export const updateShiftShiftUpdatePut = <ThrowOnError extends boolean = false>(options: Options<UpdateShiftShiftUpdatePutData, ThrowOnError>) => {
    return (options.client ?? _heyApiClient).put<UpdateShiftShiftUpdatePutResponse, UpdateShiftShiftUpdatePutError, ThrowOnError>({
        security: [
            {
                scheme: 'bearer',
                type: 'http'
            }
        ],
        url: '/shift/update',
        ...options,
        headers: {
            'Content-Type': 'application/json',
            ...options?.headers
        }
    });
};